apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 46.8.0  # Stable version (adjust if needed)
    chart: kube-prometheus-stack
    helm:
      # skipCrds: true  # Critical: Skip CRDs
      values: |
        grafana:
          defaultDashboardsEnabled: false
          adminPassword: "admin"
          sidecar:
            dashboards:
              enabled: true
              label: grafana_dashboard
          service:
            type: LoadBalancer

        prometheus:
          prometheusSpec:
            serviceMonitorSelectorNilUsesHelmValues: false  # allow all ServiceMonitors
            serviceMonitorSelector: {}                      # select all ServiceMonitors
            serviceMonitorNamespaceSelector: {}             # allow cross-namespace scraping
          service:
            type: LoadBalancer

        alertmanager:
          service:
            type: LoadBalancer
          config:
            global:
              resolve_timeout: 5m
            route:
              receiver: slack-notifications
              group_by: ['alertname']
              group_wait: 30s
              group_interval: 5m
              repeat_interval: 1h
              routes:
                - match:
                    severity: warning
                  receiver: slack-notifications
            receivers:
              - name: slack-notifications
                slack_configs:
                  - channel: '#devops-project'
                    api_url: 'https://hooks.slack.com/services/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'
                    send_resolved: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true  # Avoid large annotation errors
      - CreateNamespace=true  # Auto-create namespace